### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by SkaeX** [BrainMaestro/FCE#62]
- [x] Implementation of Controllers
  - [x] Evaluation [#96] 
  - [x] Question [#76] 
  - [x] QuestionSet [#79]
  - [x] School [#73] 
  - [x] Section [#105] 
  - [x] User [#72] 
  - [x] Semester [#80]
  - [x] Search [#99] 
- [x] JSON response functions
- [x] `201` Created response for `created` functions [#110] 
- [x] Combine multiple request files for the same controller [#112, #102]
- [x] Other operations for when sections are opened and closed (like creating keys) [#113] 
- [x] User authentication [#118]

NB:
- PR for this should be made to the `feature/implement-controllers` branch.
- Reference this in related PRs.

**Comment by BrainMaestro** [comment]
Home? Controllers should be named according to the functionality they provide. So they'll probably use a similar naming scheme as thee repositories

**Comment by tenorz007** [comment]
We don't need this, the reason we had that on the repository was because we were restructuring the repository... Just create feature branches and create PR into develop @SkaeX thoughts @BrainMaestro

**Comment by BrainMaestro** [comment]
Actually this one is fine. It's a nice way to keep progress of the controller implementation.
